### PR TITLE
Fix `sympath` documentation

### PR DESCRIPTION
**Pull request by shaopeng-gh**
Providing the right examples for user.
See https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/advanced-symsrv-use for syntax information.

### CODE REVIEW

**Review by suvamM — COMMENTED** [review]
@shaopeng-gh The changes look straightforward to me. But could you kindly add some more details in the PR description? What was wrong with the earlier examples with the lack of the `*` symbol?

**Review by michaelcfanning — APPROVED** [review]
:shipit:

**Comment by shaopeng-gh** [comment]
> @shaopeng-gh The changes look straightforward to me. But could you kindly add some more details in the PR description? What was wrong with the earlier examples with the lack of the `*` symbol?

Updated. And fixed the conflict with main. Added the link per code review, ready for merge.

**Comment by shaopeng-gh** [comment]
> See https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/advanced-symsrv-use for syntax information.

`See https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/advanced-symsrv-use for syntax information.` this is directly copied from our source code comments.

**Review by schlaman-ms — APPROVED** [review]

**Pull request merged**
