### PR TITLE
Fixes for Issue #707 (BinSkim Reports 32-bit Executables Built with CLR Support as Violating BA2015)

### PR DESCRIPTION
**Pull request by JayOfManyTrades**
I created this pull request for my fixes for the "https://github.com/microsoft/binskim/issues/707" issue I submitted.  I very thoroughly tested the changes.

The "https://github.com/microsoft/binskim#submit-pull-requests" URL explains to "Submit a Pull Request to the 'develop' branch."  However, I do not see a `develop` branch in the primary "BinSkim" Git repository.

### CODE REVIEW

**Comment by JayOfManyTrades** [comment]
@microsoft-github-policy-service agree

**Comment by michaelcfanning** [comment]
Jay, hello. Sorry for the delay looking at this, we have fallen behind but will be catching up soon. Our plan is to get all open work wrapped up, tested and shipped the week of 11/11.

I think the code fix may be better applied in the `CanAnalyzePE` method. The distinction here is that CanAnalyze is intended to filter out any scan targets for which a specific security standard can't be applied. Any 32-bit binary (that exclusively loads as 32-bit) meets this standard.

The `Analyze` method is intended strictly for scan targets that can literally fail the security standard (i.e., which have the potential to apply a security setting but do not). As another comment, we also generally always report in these methods, i.e., any return here would be associated with a 'Pass' log.

Give me a moment and I'll refactor your change a bit, then ask for you to sanity check what I do. Stand by.

**Comment by JayOfManyTrades** [comment]
Michael, thank you for your thorough, easy-to-understand reply!  Thanks also for offering to make the appropriate changes.  I gladly will test them after you have made them available.

**Comment by michaelcfanning** [comment]
Closing this as replaced by #721

**Comment by michaelcfanning** [comment]
Closing as #721 will push Jay's fix.

**Pull request closed without merging**
