### PR TITLE
1.3.5

### PR DESCRIPTION
**Pull request by michaelcfanning**
@BillyONeal 

Someone passed me a repro file for which diaSource.loadDataForExe fails to locate a pdb, which is stored alongside the binary. A call to diaSource.loadDataForPdb applied to it directly works, however. I haven't debugged into DiaSource yet.

This proposed change, in the event no symbol path is provided, explicitly checks for the PDB alongside the file and loads it if found. For the repro case, this code path wouldn't be taken if the user happened to specify a symbols path on the command-line. Instead, we could always first check for a PDB alongside the file (even if symbol path were set). That would prevent users from overriding this location .
Any thoughts? I'll see if I can step into the diasource code to see better what's happening.

### CODE REVIEW

**Comment by BillyONeal** [comment]
@michaelcfanning My concern is that I've had customers report this kind of thing before, but in such cases, the PDB has not in fact matched the binary; and we're using the PDB as the source of truth for some of the security analysis we're doing.

The first thing I'd try would be to update DIA and symsrv.dll; maybe there was a bug there that got fixed....

**Comment by michaelcfanning** [comment]
@BillyONeal point taken. in this case, user provided screenshot evidence that PDB validated against binary using at least one verification mechanism. will take a look at the possibility of an msdia140.dll update.

**Comment by BillyONeal** [comment]
Don't forget symsrv.dll :)

**Comment by michaelcfanning** [comment]
ok. checking this in for now to unblock team. I will next test update 3/other latest symbols support binaries.

**Pull request merged**
