### PR TITLE
Fix Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_* Tests

### LINKED ISSUE #666: Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_* Tests fail on a clean clone
I just pulled the latest main and merged it into my branch.  I am now seeing test failures that were not there before.  I cloned a fresh copy of the repo and see the same failures there, so it is not related to my changes.

1. `git clone https://github.com/microsoft/binskim.git binskim2`
2. `cd binskim2`
3. `BuildAndTest.cmd`

Expected: The build and tests both succeed because this is a clean clone.
Actual: The following failures occur.

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.03]     Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_NotApplicable [FAIL]
  Failed Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_NotApplicable [14 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 0
Actual:   534
  Stack Trace:
     at Microsoft.CodeAnalysis.IL.Rules.RuleTests.VerifyApplicabilityResults(BinarySkimmer skimmer, HashSet1 targets, Boolean useDefaultPolicy, AnalysisApplicability expectedApplicability, String ruleName, String expectedReasonForNotAnalyzing) in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 377
   at Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_NotApplicable() in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 1279
  Standard Output Messages:
 'BA2027:EnableSourceLink' - 'CanAnalyze' did not correctly indicate target applicability (unexpected return was 'ApplicableToSpecifiedTarget'): clangcl.pe.c.codeview.exe
 'BA2027:EnableSourceLink' - 'CanAnalyze' did not correctly indicate target applicability (unexpected return was 'ApplicableToSpecifiedTarget'): clangcl.pe.cpp.codeview.exe
 'BA2027:EnableSourceLink' - 'CanAnalyze' did not correctly indicate target applicability (unexpected return was 'ApplicableToSpecifiedTarget'): Native_x64_RustC_Rust_debuginfo2_v1.58.1.exe



[xUnit.net 00:00:01.29]     Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_Pass [FAIL]
  Failed Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_Pass [3 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 0
Actual:   326
  Stack Trace:
     at Microsoft.CodeAnalysis.IL.Rules.RuleTests.Verify(BinarySkimmer skimmer, IEnumerable1 additionalTestFiles, Boolean useDefaultPolicy, Boolean expectToPass, Boolean bypassExtensionValidation) in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 167
   at Microsoft.CodeAnalysis.IL.Rules.RuleTests.VerifyPass(BinarySkimmer skimmer, IEnumerable`1 additionalTestFiles, Boolean useDefaultPolicy, Boolean bypassExtensionValidation) in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 34
   at Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_Pass() in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 1267
  Standard Output Messages:
 Expected 'BA2027:EnableSourceLink' success but saw no result at all for file: CPlusPlus_SourceLink.exe
 Expected 'BA2027:EnableSourceLink' success but saw no result at all for file: CSharp_FullPdb_SourceLink.dll
 Expected 'BA2027:EnableSourceLink' success but saw no result at all for file: CSharp_PortablePdb_SourceLink.dll



[xUnit.net 00:00:01.58]     Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_Fail [FAIL]
  Failed Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_Fail [2 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 0
Actual:   106
  Stack Trace:
     at Microsoft.CodeAnalysis.IL.Rules.RuleTests.Verify(BinarySkimmer skimmer, IEnumerable1 additionalTestFiles, Boolean useDefaultPolicy, Boolean expectToPass, Boolean bypassExtensionValidation) in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 167
   at Microsoft.CodeAnalysis.IL.Rules.RuleTests.VerifyFail(BinarySkimmer skimmer, IEnumerable`1 additionalTestFiles, Boolean useDefaultPolicy, Boolean bypassExtensionValidation) in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 43
   at Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_Fail() in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 1273
  Standard Output Messages:
 Expected 'BA2027:EnableSourceLink' failure but saw no result at all for file: CPlusPlus_NoSourceLink.exe




Failed!  - Failed:     3, Passed:   102, Skipped:     0, Total:   105, Duration: 1 s - Test.FunctionalTests.BinSkim.Rules.dll (netcoreapp3.1)
BinSkim.Rules Functional tests execution FAILED.
Build and test did not complete successfully.
```

### PR DESCRIPTION
**Pull request by dmachaj**
Closes #666

The tests are failing because the .dll and .exe files are checked in but the .pdb files are missing.  The analysis fails when there are no PDB files so the tests all fail the same way.  

The first problem is that the SourceLink.sln which produces these test binaries is putting them in the wrong folder (`BA6001.EnableSourceLink` instead of `BA2027.EnableSourceLink`).  Fixing that and building Release|AnyCPU produces PE files in the expected location.  (PDBs may still be missing but I had already placed them manually so I'm unsure).  This also fixes an annoyance because building that .sln put a bunch of new files in Git that needed to be ignored because they are wrong.

The second problem is that some of the NotApplicable binaries are also missing PDB files.  The matching PDBs for those files are present elsewhere in the repo and simply need to be copied into the appropriate test data directory.

### CODE REVIEW

**Comment by marmegh** [comment]
For the `NotApplicable` cases, it looks like some of those were copied from other tests that did not require PDBs. @shaopeng and @eddynaka, for the Clang and Mach-O examples, those should not be included because they would have been filtered before CanAnalyze(), correct?

**Comment by dmachaj** [comment]
Nice! That did the trick.  The pipeline build is now passing.

**Comment by marmegh** [comment]
Awesome!

---
In reply to: [1190603260](https://github.com/microsoft/binskim/pull/669#issuecomment-1190603260) [](http://example.com/codeflow?ancestors=1190603260,1190603260)

**Comment by pharring** [comment]
I wanted to include those clang and rust EXEs because they are Windows PE binaries (hence picked up by WindowsBinaryAndPdb), but they should NOT be checked for SourceLink (since those compilers don't support it). There's code in the BinSkim analyzer to detect non-MSVC binaries like that.

Is there a better way to handle those cases?

**Comment by marmegh** [comment]
The code to detect non-MSVC binaries requires that the PDB file be present.

---
In reply to: [1190672024](https://github.com/microsoft/binskim/pull/669#issuecomment-1190672024) [](http://example.com/codeflow?ancestors=1190672024,1190672024)

**Comment by shaopeng-gh** [comment]
we should leave these files, they are not ELF/Dwarf files, they are just missing the pdb file and we should add them.
Can be found where they were copied from, I think the original author meant to add the pdb as well, they were just get filtered by the pdb .gitignore he added.

---
In reply to: [1190581340](https://github.com/microsoft/binskim/pull/669#issuecomment-1190581340) [](http://example.com/codeflow?ancestors=1190581340,1190566566)

**Comment by shaopeng-gh** [comment]
I think they are great test files we should have, that we are not asking people to enable something that their compiler does not support. I vote for add them back in.

---
In reply to: [1190682105](https://github.com/microsoft/binskim/pull/669#issuecomment-1190682105) [](http://example.com/codeflow?ancestors=1190682105,1190672024)

**Comment by dmachaj** [comment]
I don't mind adding them back in as long as that fixes the test.  I don't currently have Clang installed to produce PDBs for inclusion.  Would anyone be willing to push to this branch with a valid binary/pdb tuple for each of them?  @pharring do you still have the original PDBs floating around?

**Comment by shaopeng-gh** [comment]
they are in the repo. Location of the pdb files:
\binskim\src\Test.UnitTests.BinaryParsers\TestData\PE\clangcl.pe.c.codeview.pdb
\binskim\src\Test.FunctionalTests.BinSkim.Driver\BaselineTestData\clangcl.pe.cpp.codeview.pdb
\binskim\src\Test.FunctionalTests.BinSkim.Driver\BaselineTestData\Native_x64_RustC_Rust_debuginfo2_v1.58.1.pdb 

---
In reply to: [1190770316](https://github.com/microsoft/binskim/pull/669#issuecomment-1190770316) [](http://example.com/codeflow?ancestors=1190770316,1190770316)

**Comment by dmachaj** [comment]
> they are in the repo. Location of the pdb files: \binskim\src\Test.UnitTests.BinaryParsers\TestData\PE\clangcl.pe.c.codeview.pdb \binskim\src\Test.FunctionalTests.BinSkim.Driver\BaselineTestData\clangcl.pe.cpp.codeview.pdb \binskim\src\Test.FunctionalTests.BinSkim.Driver\BaselineTestData\Native_x64_RustC_Rust_debuginfo2_v1.58.1.pdb
> 
> In reply to: [1190770316](https://github.com/microsoft/binskim/pull/669#issuecomment-1190770316)

I did not realize that.  That was a pretty easy fix so now they are restored and the tests are passing locally 👍.

**Review by shaopeng-gh — APPROVED** [review]
:shipit:

**Review by marmegh — APPROVED** [review]
:shipit:

**Comment by pharring** [comment]
Thanks for working this out in my absence. It "worked on my machine" because I had the PDBs locally but the .gitignore caught me out. Sorry. I will submit a PR to exclude the test data folders from .gitignore.
Once again, sorry for the unintentional "treasure hunt".

Also, aren't unit tests supposed to run as part of PR validation? Is there an issue on that?

**Comment by dmachaj** [comment]
It seems like the build only runs if you have a branch in the main repo (not a fork of it).  That is why I had to recreate my PR to be coming from the main project instead of my private fork.

Your PR came from a fork so it looks like none of the PR validation ran: #657

**Comment by shaopeng-gh** [comment]
The PR Build did failed:
[https://dev.azure.com/mseng/1ES/_build/results?buildId=17752133&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=3d94a178-cdfb-5c90-a971-5deeccbbe043](https://dev.azure.com/mseng/1ES/_build/results?buildId=17752133&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=3d94a178-cdfb-5c90-a971-5deeccbbe043)

I suggest we enable the setting for all our repos:
"Require status checks to pass before merging" in repository's Settings > Branches
@michaelcfanning @marmegh


---
In reply to: [1191560751](https://github.com/microsoft/binskim/pull/669#issuecomment-1191560751) [](http://example.com/codeflow?ancestors=1191560751,1191560751)

**Comment by eddynaka** [comment]
As @dmachaj mentioned, we had a few issues with forks.

I made a few changes in the azure pipelines to enable it.

@shaopeng-gh , that is by default, but since we had the issue above, michael forced merged the changes.

**Pull request merged**
